/** Auto-generated from Astrum_Drift_NPC_Economy_Final_Sanity_Check.xlsx */
export const NPC_BUY_FLOOR_PRICES: Record<string, number> = {
  "100 Energy Cartridges": 10,
  "25 Energy Cartridges": 4,
  "250 Energy Cartridges": 20,
  "50 Energy Cartridges": 6,
  "500 Energy Cartridges": 38,
  "Advanced Coil Carbine": 986,
  "Advanced Mining Drill": 122,
  "Advanced Pulse Pistol": 791,
  "Advanced Rail Rifle": 1197,
  "Ancient Seed Core": 350,
  "Ancient Tech Core": 350,
  "Armor Plating": 4,
  "Basic Pickaxe": 1,
  "Battle Serum I": 17,
  "Battle Serum II": 31,
  "Battle Serum III": 80,
  "Battle Serum IV": 119,
  "Battle Serum V": 281,
  "Bio-Crystal": 25,
  "Bronze Armor Suit": 4,
  "Bronze Axe": 2,
  "Bronze Bar": 2,
  "Bronze Blade": 2,
  "Bronze Helmet": 2,
  "Bronze Spear": 1,
  "Calibrated Coil Carbine": 265,
  "Calibrated Pulse Pistol": 218,
  "Calibrated Rail Rifle": 315,
  "Circuit Board": 5,
  "Coal": 2,
  "Cobalt Armor Suit": 346,
  "Cobalt Axe": 210,
  "Cobalt Bar": 121,
  "Cobalt Blade": 173,
  "Cobalt Helmet": 173,
  "Cobalt Ore": 40,
  "Cobalt Spear": 139,
  "Copper Ore": 1,
  "Fiberleaf": 1,
  "Field Med Gel": 14,
  "Glowcap Fungus": 8,
  "Guard Gel I": 6,
  "Guard Gel II": 28,
  "Guard Gel III": 72,
  "Guard Gel IV": 109,
  "Guard Gel V": 274,
  "Hardened Bore Drill": 731,
  "Hardened Coil Carbine": 693,
  "Hardened Pulse Pistol": 547,
  "Hardened Rail Rifle": 832,
  "High-Output Bore Drill": 1027,
  "High-Output Coil Carbine": 1295,
  "High-Output Pulse Pistol": 975,
  "High-Output Rail Rifle": 1544,
  "Improved Pickaxe": 14,
  "Iridium Armor Suit": 759,
  "Iridium Axe": 456,
  "Iridium Bar": 300,
  "Iridium Blade": 381,
  "Iridium Helmet": 381,
  "Iridium Ore": 100,
  "Iridium Spear": 303,
  "Iron Armor Suit": 5,
  "Iron Axe": 4,
  "Iron Bar": 3,
  "Iron Blade": 3,
  "Iron Helmet": 3,
  "Iron Ore": 2,
  "Iron Spear": 2,
  "Med Gel": 4,
  "Medicinal Sap": 3,
  "Meteoric Armor Suit": 3119,
  "Meteoric Axe": 1898,
  "Meteoric Bar": 970,
  "Meteoric Blade": 1605,
  "Meteoric Coil Carbine": 1888,
  "Meteoric Helmet": 1561,
  "Meteoric Ore": 275,
  "Meteoric Pulse Pistol": 1475,
  "Meteoric Rail Rifle": 2261,
  "Meteoric Spear": 1312,
  "Micro Med Gel": 1,
  "Minor Med Gel": 1,
  "Mutagen Root": 65,
  "Nickel Armor Suit": 38,
  "Nickel Axe": 24,
  "Nickel Bar": 16,
  "Nickel Blade": 19,
  "Nickel Helmet": 19,
  "Nickel Ore": 8,
  "Nickel Spear": 14,
  "Obsidian Shard": 200,
  "Palladium Armor Suit": 1136,
  "Palladium Axe": 682,
  "Palladium Bar": 451,
  "Palladium Blade": 570,
  "Palladium Helmet": 570,
  "Palladium Ore": 140,
  "Palladium Spear": 454,
  "Plasma Excavator": 4749,
  "Platinum Armor Suit": 426,
  "Platinum Axe": 258,
  "Platinum Bar": 168,
  "Platinum Blade": 213,
  "Platinum Helmet": 213,
  "Platinum Ore": 65,
  "Platinum Spear": 171,
  "Power Cell": 15,
  "Precision Coil Carbine": 526,
  "Precision Mining Drill": 265,
  "Precision Pulse Pistol": 414,
  "Precision Rail Rifle": 622,
  "Prototype Coil Carbine": 81,
  "Prototype Mining Drill": 32,
  "Prototype Pulse Pistol": 62,
  "Prototype Rail Rifle": 107,
  "Quartz": 12,
  "Recovery Gel": 101,
  "Reinforced Coil Carbine": 156,
  "Reinforced Pickaxe": 8,
  "Reinforced Pulse Pistol": 121,
  "Reinforced Rail Rifle": 191,
  "Resin Bloom": 5,
  "Scrap Metal": 1,
  "Sensor Parts": 8,
  "Servo Motor": 25,
  "Silver Ore": 5,
  "Spore Pod": 1,
  "Steel Armor Suit": 11,
  "Steel Axe": 7,
  "Steel Bar": 6,
  "Steel Blade": 5,
  "Steel Helmet": 5,
  "Steel Spear": 4,
  "Survey Compound I": 13,
  "Survey Compound II": 66,
  "Survey Compound III": 105,
  "Survey Compound IV": 243,
  "Survey Compound V": 429,
  "Tech Core": 75,
  "Tin Ore": 1,
  "Titanium Armor Suit": 83,
  "Titanium Axe": 52,
  "Titanium Bar": 37,
  "Titanium Blade": 41,
  "Titanium Helmet": 41,
  "Titanium Ore": 18,
  "Titanium Spear": 31,
  "Trauma Gel": 34,
  "Tungsten Armor Suit": 143,
  "Tungsten Axe": 90,
  "Tungsten Bar": 64,
  "Tungsten Blade": 72,
  "Tungsten Helmet": 72,
  "Tungsten Ore": 30,
  "Tungsten Spear": 54,
  "Venom Gland": 12,
  "Void Armor Suit": 5043,
  "Void Axe": 3010,
  "Void Bar": 1577,
  "Void Blade": 2566,
  "Void Helmet": 2524,
  "Void Ore": 400,
  "Void Spear": 2121,
  "Void-Tuned Coil Carbine": 3331,
  "Void-Tuned Excavator": 2440,
  "Void-Tuned Pulse Pistol": 2662,
  "Void-Tuned Rail Rifle": 3950,
  "Wire Bundle": 2,
  "Yield Compound I": 5,
  "Yield Compound II": 24,
  "Yield Compound III": 74,
  "Yield Compound IV": 103,
  "Yield Compound V": 266,
};

